runtime: nodejs20

# Use standard environment (more stable and commonly supported)
env: standard

# Configure automatic scaling for standard environment
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
  # OPENAI_API_KEY should be set in Google App Engine environment
  # OPENAI_API_KEY: Set via gcloud command for security

# Build configuration
build_env_variables:
  NODE_ENV: production 