runtime: nodejs20

# Use standard environment (more stable and commonly supported)
env: standard

# Configure automatic scaling for standard environment
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  NODE_ENV: production
  OPENAI_API_KEY: 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

# Build configuration
build_env_variables:
  NODE_ENV: production 